//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotellDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking_Services
    {
        public int booking_service_id { get; set; }
        public int booking_id { get; set; }
        public int service_id { get; set; }
        public int quantity { get; set; }
        public decimal price_at_booking { get; set; }
        public decimal subtotal { get; set; }
    
        public virtual Bookings Bookings { get; set; }
        public virtual Services Services { get; set; }
    }
}
